version: '3.3'
networks:
  jokenpo:
    driver: bridge
volumes:
  jokenpo-volume: {}
services:
  jokenpo-mysql:
    container_name: jokenpo-mysql
    networks:
      - jokenpo
    build:
      dockerfile: ./.infra/mysql/Dockerfile
      context: .
    environment:
      MYSQL_DATABASE: 'jokenpo'
      MYSQL_USER: 'jokenpo'
      MYSQL_PASSWORD: 'jokenpo'
      MYSQL_ROOT_PASSWORD: 'jokenpo'
    volumes:
      - jokenpo-volume:/var/lib/mysql
    ports:
      - '3302:3306'
