version: '3.7'
networks:
  jokenpo:
    driver: bridge
volumes:
  jokenpo-mysql-volume: {}
  jokenpo-backend-volume: {}
services:
  jokenpo-mysql:
    container_name: jokenpo-mysql
    networks:
      - jokenpo
    build:
      dockerfile: ./.infra/mysql/Dockerfile
      context: .
    environment:
      MYSQL_DATABASE: 'jokenpo'
      MYSQL_USER: 'jokenpo'
      MYSQL_PASSWORD: 'jokenpo'
      MYSQL_ROOT_PASSWORD: 'jokenpo'
    volumes:
      - jokenpo-mysql-volume:/var/lib/mysql
    ports:
      - '3302:3306'
  jokenpo-backend:
    container_name: jokenpo-backend
    networks:
      - jokenpo
    build:
      dockerfile: ./.infra/backend/Dockerfile
      context: .
    volumes:
      - jokenpo-backend-volume:/app
    ports:
      - '5000:3000'
    depends_on:
      - jokenpo-mysql