database:
    user: jokenpo
    password: jokenpo
    net: tcp
    addr: jokenpo-mysql:3306
    dbname: jokenpo
    allowNativePasswords: true
    params:
        parseTime: "true"

server:
    address: 3000