database:
    user: jokenpo
    password: jokenpo
    net: tcp
    addr: 127.0.0.1:3302
    dbname: jokenpo
    allowNativePasswords: true
    params:
        parseTime: "true"

server:
    address: 5000